services:
  db:
    image: mysql:8.0.39
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: docker
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: startupdb
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - apirestfull-network
  rest-full-api-udemy:
    image: brunorodrigues2002/rest-full-api-udemy
    restart: always
    build: ./rest-full-api-udemy
    working_dir: /rest-full-api-udemy
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/startupdb?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 12345
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - apirestfull-network
networks:
    apirestfull-network:
      driver: bridge
