name: Continuous Integration with Github Actions

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build application JAR
      working-directory: ./22_DockerizingOurApp/rest-with-apring-boot-and-java-restfull
      run: mvn -B package --file pom.xml

    - name: Docker compose build
      working-directory: ./22_DockerizingOurApp
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-full-api-udemy:latest brunorodrigues2002/rest-full-api-udemy:latest ${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-full-api-udemy:latest brunorodrigues2002/rest-full-api-udemy:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-full-api-udemy:latest brunorodrigues2002/rest-full-api-udemy:latest
